os:
  - linux
  - osx

osx_image: xcode11.4
sudo: true
dist: bionic
language: node_js
node_js:
  - "14"

install:
  - npm install # npm ci wasn't working on osx/linux?

script:
  - ./scripts/travis.sh

branches:
  only:
    - master