version: 1.0.{build}

branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - git reset --hard HEAD

build_script:
  - node --version
  - npm --version
  - npm install
  - npm run dist-win

test: off