name: Create Client Release
on:
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: |
          npm install
          npm run dist-win
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IOT_CLIENT_ACCESS_KEY: ${{secrets.IOT_CLIENT_ACCESS_KEY}}
          IOT_CLIENT_SECRET_KEY: ${{secrets.IOT_CLIENT_SECRET_KEY}}
          AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
          AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: |
          npm install
          npm run dist-linux
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IOT_CLIENT_ACCESS_KEY: ${{secrets.IOT_CLIENT_ACCESS_KEY}}
          IOT_CLIENT_SECRET_KEY: ${{secrets.IOT_CLIENT_SECRET_KEY}}
  build-osx:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: |
          npm install
          npm run dist-mac
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IOT_CLIENT_ACCESS_KEY: ${{secrets.IOT_CLIENT_ACCESS_KEY}}
          IOT_CLIENT_SECRET_KEY: ${{secrets.IOT_CLIENT_SECRET_KEY}}
          APPLEID: ${{secrets.APPLEID}}
          APPLEIDPASS: ${{secrets.APPLEIDPASS}}
          CSC_LINK: ${{secrets.OSX_CSC_LINK}}
          CSC_KEY_PASSWORD: ${{secrets.OSX_CSC_KEY_PASSWORD}}